# coding: utf-8
from sqlalchemy import BigInteger, Column, DateTime, Index, TIMESTAMP, text
from sqlalchemy.dialects.mysql import BIGINT, VARCHAR
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()
metadata = Base.metadata


class TPseMonitorGasVocDay(Base):
    __tablename__ = 't_pse_monitor_gas_voc_day'
    __table_args__ = (
        Index('index', 'MONITOR_TIME', 'CREDIT_NO', 'OUTPOINT_ID', 'SYS_CITY_CODE', 'SYS_COUNTY_CODE', unique=True),
        {'comment': '污染源_废气VOC(天)'}
    )

    ID = Column(BIGINT, primary_key=True, comment='ID')
    MONITOR_TIME = Column(DateTime, comment='监测时间')
    CREDIT_NO = Column(VARCHAR(128), comment='企业信用代码')
    COMPANY_NAME = Column(VARCHAR(100), comment='企业名称')
    OUTPOINT_TYPE = Column(VARCHAR(40), comment='排口类型')
    OUTPOINT_ID = Column(BigInteger, comment='排口ID')
    OUTPOINT_NAME = Column(VARCHAR(40), comment='排口名称')
    COMPANY_STATUS = Column(VARCHAR(40), comment='企业状态')
    DEVICE_STATUS = Column(VARCHAR(40), comment='设备状态')
    PID_220 = Column(VARCHAR(30), comment='碳氢化合物(总烃)-PID')
    VAL_220 = Column(VARCHAR(10), comment='碳氢化合物(总烃)-实测值')
    CVT_220 = Column(VARCHAR(10), comment='碳氢化合物(总烃)-折算值')
    STAND_220 = Column(VARCHAR(10), comment='碳氢化合物(总烃)-标准值')
    CBBS_220 = Column(VARCHAR(10), comment='碳氢化合物(总烃)-超标倍数')
    EX_220 = Column(VARCHAR(10), comment='碳氢化合物(总烃)-排放量')
    PFL_220 = Column(VARCHAR(10), comment='截止前一天排放量')
    STATUS_220 = Column(VARCHAR(20), comment='碳氢化合物(总烃)-状态')
    PID_299 = Column(VARCHAR(30), comment='甲烷- PID\\n')
    VAL_299 = Column(VARCHAR(10), comment='甲烷-实测值')
    CVT_299 = Column(VARCHAR(10), comment='甲烷-折算值')
    STAND_299 = Column(VARCHAR(10), comment='甲烷-标准值')
    CBBS_299 = Column(VARCHAR(10), comment='甲烷-超标倍数')
    EX_299 = Column(VARCHAR(10), comment='甲烷-排放量')
    PFL_299 = Column(VARCHAR(10), comment='截止前一天排放量')
    STATUS_299 = Column(VARCHAR(20), comment='甲烷-状态')
    PID_383 = Column(VARCHAR(10), comment='非甲烷总烃-PID')
    VAL_383 = Column(VARCHAR(10), comment='非甲烷总烃-实测值')
    CVT_383 = Column(VARCHAR(10), comment='非甲烷总烃-折算值')
    STAND_383 = Column(VARCHAR(10), comment='非甲烷总烃-标准值')
    CBBS_383 = Column(VARCHAR(10), comment='非甲烷总烃-超标倍数')
    EX_383 = Column(VARCHAR(10), comment='非甲烷总烃-排放量')
    PFL_383 = Column(VARCHAR(10), comment='截止前一日排放量')
    STATUS_383 = Column(VARCHAR(20), comment='非甲烷总烃-状态')
    PID_216 = Column(VARCHAR(10), comment='苯- PID')
    VAL_216 = Column(VARCHAR(10), comment='苯-实测值')
    CVT_216 = Column(VARCHAR(10), comment='苯-折算值')
    STAND_216 = Column(VARCHAR(10), comment='苯-标准值')
    CBBS_216 = Column(VARCHAR(10), comment='苯-超标倍数')
    EX_216 = Column(VARCHAR(10), comment='苯-排放量')
    PFL_216 = Column(VARCHAR(10), comment='截止前一日排放量')
    STATUS_216 = Column(VARCHAR(20), comment='苯-状态')
    PID_214 = Column(VARCHAR(10), comment='甲苯- PID')
    VAL_214 = Column(VARCHAR(10), comment='甲苯-实测值')
    CVT_214 = Column(VARCHAR(10), comment='甲苯-折算值')
    STAND_214 = Column(VARCHAR(10), comment='甲苯-标准值')
    CBBS_214 = Column(VARCHAR(10), comment='甲苯-超标倍数')
    EX_214 = Column(VARCHAR(10), comment='甲苯-排放量')
    PFL_214 = Column(VARCHAR(10), comment='截止前一日排放量')
    STATUS_214 = Column(VARCHAR(20), comment='甲苯-状态')
    PID_376 = Column(VARCHAR(10), comment='二甲苯- PID')
    VAL_376 = Column(VARCHAR(10), comment='二甲苯-实测值')
    CVT_376 = Column(VARCHAR(10), comment='二甲苯-折算值')
    STAND_376 = Column(VARCHAR(10), comment='二甲苯-标准值')
    CBBS_376 = Column(VARCHAR(10), comment='二甲苯-超标倍数')
    EX_376 = Column(VARCHAR(10), comment='二甲苯-排放量')
    PFL_376 = Column(VARCHAR(10), comment='截止前一日排放量')
    STATUS_376 = Column(VARCHAR(20), comment='二甲苯-状态')
    VAL_209 = Column(VARCHAR(20), comment='氧气(%)')
    VAL_210 = Column(VARCHAR(20), comment='流量(m3)')
    VAL_211 = Column(VARCHAR(20), comment='流速')
    SYS_CREATE_TIME = Column(TIMESTAMP, server_default=text("CURRENT_TIMESTAMP"), comment='创建时间')
    SYS_UPDATE_TIME = Column(TIMESTAMP, server_default=text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"), comment='修改时间')
    SYS_CITY_CODE = Column(VARCHAR(20), nullable=False, server_default=text("''"), comment='所属地级市编码（实例格式：370200000000）')
    SYS_COUNTY_CODE = Column(VARCHAR(20), server_default=text("''"), comment='所属区县编码（实例格式：370283000000）')
    SYS_CREATE_NAME = Column(VARCHAR(100), server_default=text("''"), comment='创建人')
    SYS_UPDATE_NAME = Column(VARCHAR(100), server_default=text("''"), comment='修改人')
